
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`
example_test_data_ratio: 0.2
standard_scaler_data_engr: True
model_params:
  penalty: l2
  dual: False
  tol: 0.0001
  C: 1.0
  fit_intercept: True
  intercept_scaling: 1
  #class_weight: None
  #random_state: None
  solver: lbfgs
  max_iter: 100
  multi_class: auto
  verbose: 0
  warm_start: False
  #n_jobs: None
  #l1_ratio: None
